=== coi/coi-governance/RuleGenerator/bin/edu/rule/schema/org_spec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ooi.org/org_spec" xmlns:tns="http://www.ooi.org/org_spec" elementFormDefault="qualified">



    <complexType name="ACLMessageType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="action" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="sender" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="receiver" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="replyTo" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="replyBy" type="dateTime" maxOccurs="1" minOccurs="0"></element>
    		<element name="content" type="tns:ContentType" maxOccurs="1" minOccurs="0"></element>
    		<element name="language" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="encoding" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="ontology" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="protocol" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="replyWith" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    

    <complexType name="ContentType">
    	<sequence>
    		<element name="fact" type="tns:EventType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="param" type="tns:ParameterType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="OrgType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="org_name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="representative" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="power" type="tns:PowerType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="role" type="tns:RoleType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="PowerType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="action" type="tns:EventType" maxOccurs="1" minOccurs="1"></element>
    		<element name="authorization" type="tns:AuthorizationType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="RoleType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="power" type="tns:PowerType" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="capability" type="tns:CapabilityType" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="commitment" type="tns:CommitmentType" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="prohibition" type="tns:ProhibitionType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="CapabilityType">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="action" type="tns:EventType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="CommitmentType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="debtor" type="string"></element>
    		<element name="creditor" type="string"></element>
    		<element name="antecedent" type="tns:EventType" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="consequent" type="tns:EventType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="EventType">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="param" type="tns:ParameterType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="ParameterType">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<choice>
    			<element name="float_value" type="float"></element>
    			<element name="string_value" type="string"></element>
    			<element name="boolean_value" type="boolean"></element>
    			<element name="int_value" type="int"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="AuthorizationType">
    	<sequence>
    		<element name="authorization_id" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="action" type="tns:EventType" maxOccurs="1" minOccurs="1"></element>
    		<element name="grantedBy" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="grantedTo" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <element name="org" type="tns:OrgType"></element>

    <complexType name="ProhibitionType">
    	<sequence>
    		<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="prohibition_id" type="string"></element>
    		<element name="action" type="tns:EventType" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="sanction" type="tns:EventType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

</schema>

=== coi/coi-governance/RuleGenerator/bin/org_spec1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:org xmlns:tns="http://www.ooi.org/org_spec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ooi.org/org_spec org_spec.xsd ">
  <tns:org_name>tns:org_name</tns:org_name>
  <tns:representative>tns:representative</tns:representative>
  <tns:role>
    <tns:name>org</tns:name>
    <tns:power>
      <tns:name>admit</tns:name>
      <tns:action>
        <tns:name>ADMIT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value id = "mem_id">var_1</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>role</tns:name>
          <tns:string_value>var_3</tns:string_value>
        </tns:param>      
      	<tns:param>
          <tns:name>type</tns:name>
          <tns:string_value>membership</tns:string_value>
        </tns:param>
      </tns:action>
      <tns:authorization>
      <tns:authorization_id>admit_auth</tns:authorization_id>
      <tns:action>
        <tns:name>admit_req</tns:name>
        <tns:param>
          <tns:name>action</tns:name>
          <tns:string_value>REQUEST</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>sender</tns:name>
          <tns:string_value idref = "mem_id">var_1</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>receiver</tns:name>
          <tns:string_value>var_2</tns:string_value>
        </tns:param>      
      	<tns:param>
          <tns:name>type</tns:name>
          <tns:string_value>membership</tns:string_value>
        </tns:param>
      </tns:action> 
    </tns:authorization>
    </tns:power>
    <tns:power>
      <tns:name>eject</tns:name>
      <tns:action>
        <tns:name>EJECT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>member_id</tns:string_value>
        </tns:param>
      </tns:action>
      
    </tns:power>
    <tns:capability>
      <tns:name>evaluate</tns:name>
      <tns:action>
        <tns:name>EVALUATE</tns:name>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>member_id</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>role</tns:name>
          <tns:string_value>role_id</tns:string_value>
        </tns:param>
      </tns:action>
    </tns:capability>
    <tns:commitment>
      <tns:debtor>org</tns:debtor>
      <tns:creditor>member</tns:creditor>
      <tns:antecedent>
        <tns:name>eval_request</tns:name>
        <tns:param>
          <tns:name>attribute_name</tns:name>
          <tns:string_value>value</tns:string_value>
        </tns:param>
      </tns:antecedent>
      <tns:consequent>
        <tns:name>eval_response</tns:name>
        <tns:param>
          <tns:name>attribute_name</tns:name>
          <tns:boolean_value>true</tns:boolean_value>
        </tns:param>
      </tns:consequent>
    </tns:commitment>
    <tns:prohibition>
      <tns:prohibition_id>prohibit_share</tns:prohibition_id>
      <tns:action>
        <tns:name>SHARE</tns:name>
        <tns:param>
          <tns:name>object</tns:name>
          <tns:string_value>obj_id</tns:string_value>
        </tns:param>
      </tns:action>
      <tns:sanction>
        <tns:name>EJECT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>mem_id</tns:string_value>
        </tns:param>
      </tns:sanction>
    </tns:prohibition>
  </tns:role>
  <tns:role>
    <tns:name>member</tns:name>
    <tns:power>
      <tns:name>propose</tns:name>
      <tns:action>
        <tns:name>PROPOSE</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
      </tns:action>
    </tns:power>
    <tns:power>
      <tns:name>accept</tns:name>
      <tns:action>
        <tns:name>ACCEPT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>member_id</tns:string_value>
        </tns:param>
      </tns:action>
    </tns:power>
    <tns:power>
      <tns:name>reject</tns:name>
      <tns:action>
        <tns:name>REJECT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>member_id</tns:string_value>
        </tns:param>
      </tns:action>
    </tns:power>
    <tns:capability>
      <tns:name>req_evaluate</tns:name>
      <tns:action>
        <tns:name>REQ_EVALUATE</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>org_id</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>attribute_name</tns:name>
          <tns:string_value>role</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>attribute_value</tns:name>
          <tns:string_value>member</tns:string_value>
        </tns:param>
      </tns:action>
    </tns:capability>
    <tns:commitment>
      <tns:debtor>org</tns:debtor>
      <tns:creditor>member</tns:creditor>
      <tns:antecedent>
        <tns:name>eval_request</tns:name>
        <tns:param>
          <tns:name>attribute_name</tns:name>
          <tns:string_value>value</tns:string_value>
        </tns:param>
      </tns:antecedent>
      <tns:consequent>
        <tns:name>eval_response</tns:name>
        <tns:param>
          <tns:name>attribute_name</tns:name>
          <tns:boolean_value>true</tns:boolean_value>
        </tns:param>
      </tns:consequent>
    </tns:commitment>
    <tns:prohibition>
      <tns:prohibition_id>prohibit_share</tns:prohibition_id>
      <tns:action>
        <tns:name>SHARE</tns:name>
        <tns:param>
          <tns:name>object</tns:name>
          <tns:string_value>obj_id</tns:string_value>
        </tns:param>
      </tns:action>
      <tns:sanction>
        <tns:name>EJECT</tns:name>
        <tns:param>
          <tns:name>org</tns:name>
          <tns:string_value>OOI</tns:string_value>
        </tns:param>
        <tns:param>
          <tns:name>member</tns:name>
          <tns:string_value>mem_id</tns:string_value>
        </tns:param>
      </tns:sanction>
    </tns:prohibition>	
  </tns:role>
</tns:org>
